GestaoTarefasIPG/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;

namespace GestaoTarefasIPG.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly FuncionarioDbContext _context;

        public int TamanhoPagina = 10;

        public FuncionariosController(FuncionarioDbContext context)
        {
            _context = context;
        }

        // GET: Funcionarios
        public IActionResult Index(int page = 1, string searchString = "", string sort = "true", string procuraPor = "Nome") {
            var funcionarios = from p in _context.Funcionario
                              select p;

            if (!String.IsNullOrEmpty(searchString)) {
                if (procuraPor.Equals("Nome")) {
                    funcionarios = funcionarios.Where(p => p.Nome.Contains(searchString));
                } else if (procuraPor.Equals("Numero")) {
                    funcionarios = funcionarios.Where(p => p.NumeroFuncionario.Contains(searchString));
                }
            }
             

            decimal nFuncionarios = funcionarios.Count();

            int NUMERO_PAGINAS_ANTES_DEPOIS = ((int)nFuncionarios / TamanhoPagina);

            if (nFuncionarios % TamanhoPagina == 0) {
                NUMERO_PAGINAS_ANTES_DEPOIS -= 1;
            }

            FuncionariosViewModel vm = new FuncionariosViewModel {
                Sort = sort,
                PaginaAtual = page,
                PrimeiraPagina = Math.Max(1, page - NUMERO_PAGINAS_ANTES_DEPOIS),
                TotalPaginas = (int)Math.Ceiling(nFuncionarios / TamanhoPagina),
                ProcuraPor = procuraPor

            };

            if (sort.Equals("true")) {
                vm.Funcionarios = funcionarios.OrderBy(p => p.Nome).Skip((page - 1) * TamanhoPagina).Take(TamanhoPagina);
            } else {
                vm.Funcionarios = funcionarios.OrderByDescending(p => p.Nome).Skip((page - 1) * TamanhoPagina).Take(TamanhoPagina);
            }

            vm.UltimaPagina = Math.Min(vm.TotalPaginas, page + NUMERO_PAGINAS_ANTES_DEPOIS);
            vm.StringProcura = searchString;

            return View(vm);
        }

        // GET: Funcionarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionario
                .FirstOrDefaultAsync(m => m.FuncionarioId == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // GET: Funcionarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Funcionarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FuncionarioId,Nome,Contacto,Email,NumeroFuncionario")] Funcionario funcionario) {
            if (ModelState.IsValid) {

                ViewBag.Email = "";
                ViewBag.Contacto = "";
                ViewBag.NumeroFunc = "";

                bool erro = false;

                var Email = _context.Funcionario
                .FirstOrDefault(m => m.Email == funcionario.Email);

                var Contacto = _context.Funcionario
                .FirstOrDefault(m => m.Contacto == funcionario.Contacto);
                
                var NumeroFunc = _context.Funcionario
                .FirstOrDefault(m => m.NumeroFuncionario == funcionario.NumeroFuncionario);

                if (Email != null) {
                    ViewBag.Email = "O Email " + funcionario.Email + " já foi usado";
                    erro = true;
                }
                if (Contacto != null) {
                    ViewBag.Contacto = "O contacto " + funcionario.Contacto + " já foi usado";
                    erro = true;
                }
                if (NumeroFunc != null) {
                    ViewBag.NumeroFunc = "O número de funcionário " + funcionario.NumeroFuncionario + " já foi usado";
                    erro = true;
                }

                if (erro == false) {

                    _context.Add(funcionario);
                    await _context.SaveChangesAsync();
                    ViewBag.Title = "Criação bem sucedida!";
                    ViewBag.Message = "Funcionário criado com sucesso";
                    return View("Success");

                } else {
                    return View("Create");

                }
            }
                return View(funcionario);
        }
        // GET: Funcionarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionario.FindAsync(id);
            if (funcionario == null)
            {
                return NotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FuncionarioId,Nome,Contacto,Email,NumeroFuncionario")] Funcionario funcionario)
        {
            if (id != funcionario.FuncionarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(funcionario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuncionarioExists(funcionario.FuncionarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                ViewBag.Title = "Atualização bem sucedida!";
                ViewBag.Message = "Funcionário atualizado com sucesso";
                return View("Success");
            }
            return View(funcionario);
        }

        // GET: Funcionarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionario
                .FirstOrDefaultAsync(m => m.FuncionarioId == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var funcionario = await _context.Funcionario.FindAsync(id);
            _context.Funcionario.Remove(funcionario);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            ViewBag.Title = "Eliminação bem sucedida!";
            ViewBag.Message = "Funcionário eliminado com sucesso";
            return View("Success");
        }

        private bool FuncionarioExists(int id)
        {
            return _context.Funcionario.Any(e => e.FuncionarioId == id);
        }
    }
}

GestaoTarefasIPG/Controllers/ProfessoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using System.Net.Mail;
using System.Net;

namespace GestaoTarefasIPG.Controllers
{
    public class ProfessoresController : Controller
    {
        private readonly ProfessorDbContext _context;

        public int TamanhoPagina = 10;

        public ProfessoresController(ProfessorDbContext context)
        {
            _context = context;
        }

        // GET: Professores
        public IActionResult Index(int page = 1, string searchString = "", string sort = "true", string procuraPor = "Nome")
        {
            var professores = from p in _context.Professor
                              select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (procuraPor.Equals("Nome"))
                {
                    professores = professores.Where(p => p.Nome.Contains(searchString));
                }
                else if (procuraPor.Equals("Gabinete"))
                {
                    professores = professores.Where(p => p.Gabinete.Contains(searchString));
                }
                else if (procuraPor.Equals("Numero"))
                {
                    professores = professores.Where(p => p.NumFuncionario.Contains(searchString));
                }
            }

            decimal nProfessores = professores.Count();

            int NUMERO_PAGINAS_ANTES_DEPOIS = ((int)nProfessores / TamanhoPagina);

            if (nProfessores % TamanhoPagina == 0)
            {
                NUMERO_PAGINAS_ANTES_DEPOIS -= 1;
            }

            ProfessoresViewModel vm = new ProfessoresViewModel
            {
                Sort = sort,
                PaginaAtual = page,
                PrimeiraPagina = Math.Max(1, page - NUMERO_PAGINAS_ANTES_DEPOIS),
                TotalPaginas = (int)Math.Ceiling(nProfessores / TamanhoPagina),
                ProcuraPor = procuraPor
            };

            if (sort.Equals("true"))
            {
                vm.Professores = professores.OrderBy(p => p.Nome).Skip((page - 1) * TamanhoPagina).Take(TamanhoPagina);
            }
            else
            {
                vm.Professores = professores.OrderByDescending(p => p.Nome).Skip((page - 1) * TamanhoPagina).Take(TamanhoPagina);
            }

            vm.UltimaPagina = Math.Min(vm.TotalPaginas, page + NUMERO_PAGINAS_ANTES_DEPOIS);
            vm.StringProcura = searchString;

            return View(vm);
        }

        // GET: Professores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professor
                .FirstOrDefaultAsync(m => m.ProfessorId == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // GET: Professores/Create
        public IActionResult Create()
        {
            ViewBag.ErrorEmail = "";
            ViewBag.ErrorNum = "";
            ViewBag.ErrorFunc = "";

            return View();
        }

        // POST: Professores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProfessorId,Nome,NumeroTelemovel,Email,Gabinete,NumFuncionario")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                var professores = _context.Professor.FirstOrDefault(p => p.Email == professor.Email);

                bool error = false;

                if (professores != null)
                {
                    error = true;
                    ViewBag.ErrorEmail = "email";
                }
                else
                {
                    ViewBag.ErrorEmail = "";
                }

                professores = _context.Professor.FirstOrDefault(p => p.NumeroTelemovel == professor.NumeroTelemovel);

                if (professores != null)
                {
                    error = true;
                    ViewBag.ErrorNum = "num";
                }
                else
                {
                    ViewBag.ErrorNum = "";
                }

                professores = _context.Professor.FirstOrDefault(p => p.NumFuncionario == professor.NumFuncionario);

                if (professores != null)
                {
                    error = true;
                    ViewBag.ErrorFunc = "func";
                }
                else
                {
                    ViewBag.ErrorFunc = "func";
                }

                if (error)
                {
                    return View();
                }

                _context.Add(professor);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Professor criado com sucesso!!";

                try
                {
                    var subject = "Conta IPG";
                    var body = "A sua conta IPG foi criada";

                    var senderEmail = new MailAddress("ipg.app.pi@gmail.com", "IPG");
                    var password = "olaolaola";

                    var receiverEmail = new MailAddress(professor.Email, professor.Nome);
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(senderEmail.Address, password)
                    };
                    using (var mess = new MailMessage(senderEmail, receiverEmail)
                    {
                        Subject = subject,
                        Body = body
                    })
                    {
                        smtp.Send(mess);
                    }

                    return View("sucesso");
                }
                catch (Exception)
                {
                    ViewBag.Error = "Some Error";
                }

            }
            return View(professor);
        }

        // GET: Professores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professor.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }
            return View(professor);
        }

        // POST: Professores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProfessorId,Nome,NumeroTelemovel,Email,Gabinete,NumFuncionario")] Professor professor)
        {
            if (id != professor.ProfessorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.ProfessorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        // GET: Professores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professor
                .FirstOrDefaultAsync(m => m.ProfessorId == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // POST: Professores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var professor = await _context.Professor.FindAsync(id);
            _context.Professor.Remove(professor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessorExists(int id)
        {
            return _context.Professor.Any(e => e.ProfessorId == id);
        }
    }
}

GestaoTarefasIPG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/Favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <title>Gestão de tarefas do IPG</title>

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">
</head>

@*Old Head*@

@*<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - GestaoTarefasIPG</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>*@

<body id="page-top">

    <style>
        nav {
            background-color: #db1033;
        }

        .link {
            color: white;
        }

            .link:hover {
                color: white;
                text-decoration: none;
            }

        html, body {
            height: 100%;
            width: 100%;
            margin: 0;
            display: table;
        }

        footer {
            text-align: center;
            display: table-row;
            height: 0;
        }

        .footerLink {
            color: #db1033;
        }

            .footerLink:hover {
                color: grey;
                text-decoration: none;
            }

        .div2 {
            float: right;
            height: 40px;
            padding-top: 8px;
            padding-right: 10px;
        }
    </style>

    <header>

        <nav>
            <img src="~/logo.png" width="25" height="40" />
            <a class="link" asp-area="" asp-controller="Home" asp-action="Index">Gestão IPG</a>
            &nbsp;
            <a class="link" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionários</a>
            &nbsp;
            <a class="link" asp-area="" asp-controller="Professores" asp-action="Index">Professores</a>
            <partial name="_LoginPartial" />
        </nav>

        @*Old nav*@

        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestaoTarefasIPG</a>--
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>*@
    </header>

    <div id="wrapper">

        <div id="content-wrapper">

            <div class="container-fluid">

                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="background-color: white;">
            &copy; 2019 - GestaoTarefasIPG - <a class="footerLink" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin.min.js"></script>

    <script src="~/js/site.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>